# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307def50c3cd934c1ad28404576d47f80ae3627c8704d45276f7b14dedb2b204d49587c43bbb5e4aa9d521dceecf774afed45a4548b1339eec1182f4a68881e7

test:
  secret_key_base: 6c8a5ab76f6c1f14654798ff55227aa302b8e33037561004ffb1ae2d3751a877dd9bab906b9bedace3f855dc4ca72c91eb78b60ff8ab9089cb98b09edd3f7967

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
